"""add status and error columns to analyses

Revision ID: 394ef58b3eb0
Revises: 724fbefc7c9c
Create Date: 2026-04-08 17:31:02.020472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "394ef58b3eb0"
down_revision: Union[str, Sequence[str], None] = "724fbefc7c9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE analysisstatus AS ENUM ('completed', 'pending', 'error')")
    op.add_column(
        "analyses",
        sa.Column(
            "status",
            sa.Enum("completed", "pending", "error", name="analysisstatus"),
            nullable=True,
        ),
    )
    op.add_column("analyses", sa.Column("error", sa.String(), nullable=True))
    op.execute("UPDATE analyses SET status = 'completed'")
    op.alter_column("analyses", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "error")
    op.drop_column("analyses", "status")
    op.execute("DROP TYPE analysisstatus")
    # ### end Alembic commands ###
