"""add processing status, attempts, comment_posted_at

Revision ID: f0fd61a55417
Revises: 394ef58b3eb0
Create Date: 2026-10-08 19:40:19.680738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f0fd61a55417"
down_revision: Union[str, Sequence[str], None] = "394ef58b3eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE analysisstatus ADD VALUE IF NOT EXISTS 'processing'")

    op.add_column(
        "analyses",
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "analyses",
        sa.Column("comment_posted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "comment_posted_at")
    op.drop_column("analyses", "attempts")
    # ### end Alembic commands ###
